# action.yml
name: 'ChatGPT CLI action'
description: 'Use bash + ChatGPT to automate github tasks'
inputs:
  type: 
    description: 'GitHub API type'
  url:  # id of input
    description: 'GitHub API object'
    required: true
outputs:
  output: # id of output
    description: 'stuff'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.type }}