on:
    workflow_call:
      inputs:
        url:
          required: true
          type: string
        possible_labels:
          required: true
          type: string
        unlabeled_only:
          required: false
          type: boolean
          default: true
      secrets:
        OPENAI_API_KEY:
          required: true
        GH_TOKEN:
          required: true

jobs:
  label_issue:
    runs-on: ubuntu-latest
    name: Label Issue
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
            repository: moxious/chatgpt-cli-action
      - name: Determine if this workflow needs to run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        id: check_run
        if: inputs.unlabeled_only
        run: |
          labels=$(gh issue view --json labels --jq .labels[].name ${{ inputs.url }})
          if [[ "$labels" ]]; then 
            echo "This issue already has labels, so we won't run the triage bot."
            gh run cancel ${{ github.run_id }}
          fi          
      - name: Determine automatic labeling
        uses: ./ # Uses an action in the root directory
        id: label_issue
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          url: ${{ inputs.url }}
          type: issue
          prompt: |
            I want you to help me categorize a GitHub issue by applying the right GitHub label to the issue, and help me 
            generate a summary of that issue.
              
            I want JSON output of a single object, containing two keys, "labels", and "summary".

            The labels key is an array of strings, 1-4 total labels.  Please try to choose at least one area label,
            and at least one type label.

            The summary key is a short plain text summary of the issue, no more than one paragraph, 
            preferably 1-2 sentences at maximum.

            Please choose labels only from this list:
            ${{ inputs.possible_labels }}
      - name: Output
        run: |
          echo '${{ steps.label_issue.outputs.output }}'
          echo '${{ steps.label_issue.outputs.errors }}'
      - name: Comment
        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cat >$HOME/outputs.txt <<EOT
          ${{ steps.label_issue.outputs.output }}
          EOT

          cat >$HOME/errors.txt <<EOT
          ${{ steps.label_issue.outputs.errors }}
          EOT

          labels=$(cat $HOME/outputs.txt | jq -r .labels[])
          summary=$(cat $HOME/outputs.txt | jq -r .summary)
          
          cat > $HOME/gh_comment.txt <<EOT
          Triage summary: $summary
          Recommended labels:

          $labels
          EOT

          gh issue comment ${{ inputs.url }} --body-file $HOME/gh_comment.txt
      - name: Add labels
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cat $HOME/outputs.txt
          for tag in $(cat $HOME/outputs.txt | jq -r .labels[] ) ; do 
            if [[ "$tag" == "labels:" ]]
            then
               continue
            fi
            echo "'$tag'" ; 
            gh issue edit ${{ inputs.url }} --add-label "$tag" ;
          done
  
