on:
    workflow_call:
      inputs:
        url:
          required: true
          type: string
        possible_labels:
          required: true
          type: string
        unlabeled_only:
          required: false
          type: boolean
          default: true
      secrets:
        OPENAI_API_KEY:
          required: true
        GH_TOKEN:
          required: true

jobs:
  label_issue:
    runs-on: ubuntu-latest
    name: Label Issue
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
            repository: moxious/chatgpt-cli-action
      - name: Determine if this workflow needs to run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        id: should_run
        if: inputs.unlabeled_only
        run: |
          labels=$(gh issue view --json labels --jq .labels[].name ${{ inputs.url }})
          if [[ "$labels" ]]; then
            echo "This issue already has labels, so we won't run the triage bot."
            exit 1
          fi          
      - name: Determine automatic labeling
        uses: ./ # Uses an action in the root directory
        id: label_issue
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          url: ${{ inputs.url }}
          type: issue
          prompt: |
            I want you to help me categorize a GitHub issue by applying the right GitHub label to the issue, and help me 
            generate a summary of that issue.
              
            I want JSON output of a single object, containing two keys, "labels", and "summary".

            The labels key should be an array of strings, 1-4 total labels.

            The summary key should be a short plain text summary of the issue, no more than one paragraph, 
            preferably 1-2 sentences at maximum.

            You may choose labels only from this list below. Do not emit labels that are not in this list, this would be incorrect
            output. Please try to choose at least one of the items below that starts with "area/" because this tells us 
            which of our identified areas applies, and choose at least one of the items below that starts with "type/" because
            this tells us what kind of issue it is.  

            The list of labels to choose from:
            ${{ inputs.possible_labels }}
      - name: Output
        run: |
          cat <<EOT
          ${{ steps.label_issue.outputs.output }}'
          EOT
          echo "Errors:"
          cat <<EOT
          ${{ steps.label_issue.outputs.errors }}
          EOT
      - name: Comment
        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cat >$HOME/outputs.txt <<EOT
          ${{ steps.label_issue.outputs.output }}
          EOT

          cat >$HOME/errors.txt <<EOT
          ${{ steps.label_issue.outputs.errors }}
          EOT

          labels=$(cat $HOME/outputs.txt | jq -r .labels[])
          summary=$(cat $HOME/outputs.txt | jq -r .summary)
          
          cat > $HOME/gh_comment.txt <<EOT
          **Triage summary**: $summary

          **Recommended labels**:

          $labels
          EOT

          gh issue comment ${{ inputs.url }} --body-file $HOME/gh_comment.txt
      - name: Add labels
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cat $HOME/outputs.txt
          cat $HOME/outputs.txt | jq -r .labels[] > $HOME/labels.txt
          echo "Extracted labels:"
          cat $HOME/labels.txt

          while IFS= read -r tag; do 
            echo "'$tag'" ; 
            gh issue edit ${{ inputs.url }} --add-label "$tag" ;
          done < $HOME/labels.txt
